export const DAILY_POST_ADMIN_REPORT_TEMPLATE = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{{subject}}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet">
</head>
<body style="margin:0; padding:0; background-color:#f3f4f6; font-family:'Inter', sans-serif; color:#111827;">
  <center>
    <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f3f4f6;">
      <tr>
        <td align="center">
          <table width="700" cellpadding="0" cellspacing="0" style="max-width:700px; background-color:#ffffff; border-radius:12px; border:1px solid #e5e7eb;">
            <!-- Header -->
            <tr>
              <td style="padding:20px; background:#1f2937; color:#fff; border-radius:12px 12px 0 0;">
                <h2 style="margin:0; font-size:20px;">Daily Post Email Report</h2>
              </td>
            </tr>

            <!-- Stats -->
            <tr>
              <td style="padding:20px; font-size:15px; line-height:1.6; color:#374151;">
                <p><strong>Total Users Emailed:</strong> {{totalUsers}}</p>
                <p><strong>Success:</strong> {{successCount}}</p>
                <p><strong>Failed:</strong> {{failedCount}}</p>
                <p><strong>Posts Included:</strong> {{postCount}}</p>
              </td>
            </tr>

            <!-- Failures Table -->
            {{#if failedUsers.length}}
            <tr>
              <td style="padding:0 20px 20px 20px;">
                <h3 style="margin:0 0 10px; font-size:16px;">Failed Deliveries</h3>
                <table width="100%" cellpadding="6" cellspacing="0" style="border-collapse:collapse; font-size:13px;">
                  <thead style="background-color:#f9fafb;">
                    <tr>
                      <th align="left">Email</th>
                      <th align="left">Error</th>
                    </tr>
                  </thead>
                  <tbody>
                    {{#each failedUsers}}
                    <tr>
                      <td style="border-top:1px solid #e5e7eb;">{{this.email}}</td>
                      <td style="border-top:1px solid #e5e7eb;">{{this.error}}</td>
                    </tr>
                    {{/each}}
                  </tbody>
                </table>
              </td>
            </tr>
            {{/if}}

            <!-- Footer -->
            <tr>
              <td style="background-color:#f9fafb; padding:20px; font-size:12px; color:#6b7280; text-align:center; border-top:1px solid #e5e7eb;">
                Automated report generated by inkshaa.<br/>
                <a href="https://readzio.com/admin" style="color:#2563eb;">View Admin Dashboard</a>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </center>
</body>
</html>`;
