services:
  - type: web
    name: inkshaa
    env: node
    buildCommand: npm run setup-client
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://readzio.com
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: your-mongo-url
      - key: JWT_SECRET
        value: your-secret
      # Add other keys like SMTP_PASS, RAZORPAY_KEY, etc. as needed
    plan: free
    autoDeploy: true
